# AGV 数据源配置
# 各小车URL配置（后期修改这里即可，无需重新编译）

XQC-1.url=http://192.168.0.9:10001/Les/Agv/CarPanel/XQC-1
XQE-122-1.url=http://192.168.0.9:10001/Les/Agv/CarPanel/XQE-122-1
XQE-122-2.url=http://192.168.0.9:10001/Les/Agv/CarPanel/XQE-122-2
